/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrameUtama.java
 *
 * Created on May 12, 2013, 6:09:05 PM
 */
package strukturdata.antrian_bank;

import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import strukturdata.antrian_bank.dialog.DialogAntrianCS;
import strukturdata.antrian_bank.dialog.DialogAntrianTeller;
import strukturdata.antrian_bank.dialog.DialogManageCS;
import strukturdata.antrian_bank.dialog.DialogManageTeller;
import strukturdata.antrian_bank.tool.CenterLocation;

import strukturdata.antrian_bank.tool.RunAntrianCS;
import strukturdata.antrian_bank.tool.RunAntrianTeller;
import strukturdata.antrian_bank.tool.StopWatchku;
import strukturdata.antrian_bank.tool.Waktu;
import strukturdata.antrian_bank.tool.WaktuPelayanan;
import strukturdata.antrian_bank.tool.Waktuku;
import strukturdata.linkedlist.LatihanList;

/**
 *
 * @author jun
 */
public class FrameUtama extends javax.swing.JFrame{
    StopWatchku stopWatch;
    Waktu w[];
    public static boolean runOto=true;
    public static int jumlahAntrianTeller=0;
    public static int jumlahAntrianCS=0;
    public static int waktuMulaiTeller=10;
    public static int waktuMulaiCS=10;
    /** Creates new form FrameUtama */
    public FrameUtama() {
      
            initComponents();
            RunAntrianTeller run=new RunAntrianTeller(this.jTable2, this.jTable3);
            RunAntrianCS run1=new RunAntrianCS(this.jTable4, this.jTable1);
            //RunAll jalankan=new RunAll(jTable1, jTable2, jTable3, jTable4) ;
            
                
            
            //DefaultTableModel m=(DefaultTableModel) this.jTable1.getModel();
           
            
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        tombolTeller = new javax.swing.JButton();
        tombolCS = new javax.swing.JButton();
        tombolReset = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel5 = new javax.swing.JPanel();
        ketTeller = new javax.swing.JLabel();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToolBar2 = new javax.swing.JToolBar();
        jPanel6 = new javax.swing.JPanel();
        jSplitPane4 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jToolBar3 = new javax.swing.JToolBar();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jToolBar4 = new javax.swing.JToolBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Antrian Bank");
        getContentPane().setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(300);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jSplitPane2.setDividerLocation(250);

        jPanel1.setLayout(new java.awt.GridLayout(5, 2));

        tombolTeller.setText("Antrian Teller");
        tombolTeller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolTellerActionPerformed(evt);
            }
        });
        jPanel1.add(tombolTeller);

        tombolCS.setText("Antrian CS");
        tombolCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolCSActionPerformed(evt);
            }
        });
        jPanel1.add(tombolCS);

        tombolReset.setText("Manage Teller");
        tombolReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolResetActionPerformed(evt);
            }
        });
        jPanel1.add(tombolReset);

        jButton1.setText("Manage CS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jScrollPane4.setViewportView(jPanel1);

        jSplitPane2.setLeftComponent(jScrollPane4);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Teller"));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jTable3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTable3.setForeground(new java.awt.Color(0, 0, 255));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "", "", "", ""}
            },
            new String [] {
                "Teller", "Melayani nomer", "Waktu", "Waktu Pelayanan", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setRowHeight(30);
        jTable3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jTable3);

        jPanel4.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jToolBar1.setRollover(true);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));
        jPanel5.add(ketTeller);

        jToolBar1.add(jPanel5);

        jPanel4.add(jToolBar1, java.awt.BorderLayout.PAGE_END);

        jSplitPane2.setRightComponent(jPanel4);

        jSplitPane1.setTopComponent(jSplitPane2);

        jSplitPane3.setDividerLocation(500);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Customer Service"));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "", "", "", ""}
            },
            new String [] {
                "CS", "Melayani nomer", "Waktu", "Waktu Pelayanan", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jToolBar2.setRollover(true);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));
        jToolBar2.add(jPanel6);

        jPanel3.add(jToolBar2, java.awt.BorderLayout.PAGE_END);

        jSplitPane3.setLeftComponent(jPanel3);

        jSplitPane4.setDividerLocation(300);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Antrian Teller"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jTable2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable2.setForeground(new java.awt.Color(123, 0, 67));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Urut", "Status", "Waktu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setRowHeight(25);
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jToolBar3.setRollover(true);
        jPanel2.add(jToolBar3, java.awt.BorderLayout.PAGE_END);

        jSplitPane4.setRightComponent(jPanel2);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Antrian Customer Service"));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jTable4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable4.setForeground(new java.awt.Color(123, 0, 67));
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Urut", "Status", "Waktu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable4.setRowHeight(25);
        jScrollPane5.setViewportView(jTable4);

        jPanel8.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        jToolBar4.setRollover(true);
        jPanel8.add(jToolBar4, java.awt.BorderLayout.PAGE_END);

        jSplitPane4.setLeftComponent(jPanel8);

        jSplitPane3.setRightComponent(jSplitPane4);

        jSplitPane1.setRightComponent(jSplitPane3);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolResetActionPerformed
       DialogManageTeller manageTeller=new DialogManageTeller(this, true, this.jTable3);
       CenterLocation c=new CenterLocation(manageTeller);
       manageTeller.setVisible(true);
    }//GEN-LAST:event_tombolResetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DialogManageCS manageCS=new DialogManageCS(this, true, this.jTable1);
       CenterLocation c=new CenterLocation(manageCS);
       manageCS.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tombolTellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolTellerActionPerformed
        DialogAntrianTeller teller=new DialogAntrianTeller(this, true,this.jTable2);
        CenterLocation center=new CenterLocation(teller);
        teller.setVisible(true);
    }//GEN-LAST:event_tombolTellerActionPerformed

    private void tombolCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolCSActionPerformed
        DialogAntrianCS cs=new DialogAntrianCS(this, true,this.jTable4);
        CenterLocation center=new CenterLocation(cs);
        cs.setVisible(true);
    }//GEN-LAST:event_tombolCSActionPerformed
    public void runperKlik(int cek){
        String no_antrian="";
                String waktu_antrian="";
                int [] value=LatihanList.cariPrioritas();
                DefaultTableModel m=(DefaultTableModel)this.jTable2.getModel();
                for(int i=0;i<m.getRowCount();i++){
                    if(value[1]==Integer.parseInt(
                        m.getValueAt(i, 0).toString())){
                        no_antrian=m.getValueAt(i, 0).toString();
                        waktu_antrian=m.getValueAt(i, 2).toString();
                        DefaultTableModel m3=(DefaultTableModel)this.jTable3.getModel();                        
                        m3.setValueAt(no_antrian, cek, 1);
                        m3.setValueAt(waktu_antrian, cek, 2);
                        
                        m.removeRow(i);
                        LatihanList.deleteKeretaPrioritas(value[0]);
                        LatihanList.cetakAntrianTeller();
                    }
                }
                StopWatchku sto=new StopWatchku(new Waktuku(0, 0, 0));
                
                WaktuPelayanan w=new WaktuPelayanan(sto,
                        jTable3, 
                        Integer.parseInt(this.jTable3.getValueAt(cek, 0).toString()), 
                        Integer.parseInt(waktu_antrian),true);
    }
    public void runOtomatis(){
        DefaultTableModel m=(DefaultTableModel)this.jTable3.getModel();
        
        while(this.jTable2.getRowCount()>0){
            //for(int i=0;i<m.getRowCount();i++){
            int i=0;
            while(i<m.getRowCount()){
                if(m.getValueAt(i, 4).toString().equalsIgnoreCase("")){
                    this.runperKlik(i);
                    System.out.println("ok "+i);
                }
                i++;
                
            }
            //}
                
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                        UIManager.setLookAndFeel(
                          UIManager.getSystemLookAndFeelClassName());
                    } catch (Exception e) { }
                FrameUtama f=new FrameUtama();
                f.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JLabel ketTeller;
    private javax.swing.JButton tombolCS;
    private javax.swing.JButton tombolReset;
    private javax.swing.JButton tombolTeller;
    // End of variables declaration//GEN-END:variables

    

    
}
